# Generated by Django 4.2 on 2023-05-24 02:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0003_remove_team_team_leader_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=128, unique=True)),
                ('member_code', models.CharField(max_length=128, unique=True)),
                ('member_desc', models.TextField(blank=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('team_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.team')),
            ],
            options={
                'db_table': 'race_member',
            },
        ),
    ]
