# Generated by Django 4.2 on 2023-05-23 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=128, unique=True)),
                ('team_member', models.JSONField(blank=True)),
                ('team_group', models.CharField(blank=True, max_length=128)),
                ('team_win', models.IntegerField(default=0)),
                ('team_lose', models.IntegerField(default=0)),
                ('team_desc', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'race_team',
            },
        ),
    ]
