# Generated by Django 4.2 on 2023-05-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_leader_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
